config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  root 'application#index'
    resources :users, :only => [:index]
    resources :categories, :except => [:show]
    resources :comments, :only => [:index]
    resources :comments, :only => [:index]
    resources :attendances,:only => [:index]
    resources :likes, :only => [:index]
  end

  devise_for :users
root 'home#index'

  resources :events do
    resources :comments
    resources :attendances, only: [:create]
    resources :likes, :only => [:create]
    resources :tags, :only => [:show]
  end

  resources :users, only: [:show]
  resources :categories, :only => [:show]
mount ActionCable.server => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :tag_list
  extend FriendlyId
  searchkick
  friendly_id :title, use: :slugged
  validates_presence_of :title, :venue, :location
  validates_length_of :title, minimum: 5

  belongs_to :organizer, class_name: "User", foreign_key:  "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, :dependent => :destroy
  has_many :attendees, through: :attendances
  has_many :likes, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  scope :recent_go_first, lambda { order(created_at: :desc)}
  mount_uploader :image, EventUploader


  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags = tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end

  def seats_left
    seats -  attendees.count
  end

  def seats_left?
     seats == attendees.count
  end

  def likes_total
    likes.where(like: "like").count
  end

  def dislikes_total
    likes.where(like: "dislike").count
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  prepend_before_action :set_event, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    if params[:query].present?
      @events = Event.search(params[:query])

    else
      @events = Event.recent_go_first.paginate(page: params[:page], per_page: 5)

    end
    @categories = Category.order(:name)



 authorize @events, :index?
  end


  def show
    authorize @event, :show?
    @comments = @event.comments.paginate(page: params[:page], per_page: 5)

    @comment = Comment.new
    @comment.event_id = @event.id


  end

  def new

    @event =Event.new


    authorize @event, :new?


  end

  def create
    @event =Event.new(event_params)
    @event.organizer =  current_user
    authorize @event, :create?


    if @event.save
    redirect_to @event, notice: "Event created!"
  else
    flash.now[:alert] = "Failed to create event :("
    render "new"

  end
  end

  def  edit
    authorize @event

  end

  def update
    authorize @event, :update?
    if @event.update_attributes(event_params)
      redirect_to @event, notice:  "You have updated event successfully"
    else
      flash.now[:alert] = "Event was nt updated"
      render 'edit'


    end
  end

  def destroy
    authorize @event, :destroy?
    if @event.destroy
      redirect_to  events_path, notice: "You have deleted event successfulle"




    end

  end


  private
  def event_params
    params.require(:event).permit(:title, :description, :start_date, :end_date, :venue, :location, :image, :category_id, :seats, :tag_list)


  end

  def set_event
    @event = Event.friendly.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] ="The page you requested does not exists"
    redirect_to events_path

  end



end

app/helpers/events_helper.rb
module EventsHelper

 def image_present(object,height: 400, width: 200)

   unless object.image.blank?
    object.image.url
  else

 "http://lorempixel.com/#{height}/#{width}"

end

 end

  def hidden? evt
   if evt.seats_left?
    "hidden"

   end
  end
end

app/views/events/_event.html.haml
.row
  .col-sm-8.col-sm-offser-2


    = simple_form_for(@event) do |f|

      = f.input :title


      = f.input :description


      = f.input :start_date,as: :datetime, start_year: Date.today.year, ampm: true,order: [:day, :month, :year]

      = f.input :end_date,as: :datetime, start_year: Date.today.year, ampm: true,order: [:day, :month, :year]

      = f.input :venue

      = f.input :location
      = f.input :category_id, collection: Category.all, label: "Select Category", prompt: true
      = f.input :seats, label: "Capacity", hint: "The number of attendees  to the event"
      = f.input :tag_list, label: "Tags", hint: "Please enter comma separated words only"
      = f.input :image, as: :file, label: "Upload Event Image"

      = f.submit class: "btn btn-primary"

      %p= link_to "Back", events_path

app/views/events/edit.html.haml
%header
  %h1 Edit

= render 'event'

app/views/events/index.html.haml
%header
  %h1 All events

  %ul.actions
    %li= link_to "New Event", new_event_path, class: 'new' if policy(Event).new?

.row
  .col-sm-3.pull-right
    .sidebar
      %h3.discover Discover
      %ul.nav.nav-pills.nav-stacked
        %li{:class => "#{active? events_path}"}
          = link_to "All EVENTS", events_path
        - @categories.each do |cat|
          %li{:class => "#{active_category?(cat)} text-uppercase"}= link_to cat.name, category_path(cat)

  .search
    .col-sm-9
      %h4 Discover and register to aatend your favourite events right here
      = form_tag events_path, class: "form-horizontal", method: :get do

        .form-group.form-group-lg
          .col-sm-10
            = text_field_tag :query, params[:query], placeholder: "search events here", autofocus: true, class: "form-control"
          .col-sm-2
            = submit_tag "Find", class: "btn btn-default btn-lg"
            - if params[:query]
              = link_to "Clear", events_path

  - @events.each do |event|
    .col-sm-9.pull-left
      = link_to  event do
        .events
          .row
            .col-sm-3
              = image_tag image_present(event, height: 400, width: 200), class: "event-image"

            .col-sm-9
              %h3.event-title= event.title
              %p
                %span.event-venue= event.venue.concat("-")
                %strong= event.location
              %p.lead-time
                %span.event-start= format_time event.start_date
                %span.pull-right Organized by #{event.organizer.username}

              %p.index-icons
                %span= fa_icon "comments"
                %span= fa_icon "thumbs-o-up"
                = event.likes_total
                %span= fa_icon "thumbs-o-down"
                = event.dislikes_total




.text-center
  = will_paginate @events

app/views/events/new.html.haml
%h1 New event

= render 'event'

app/views/events/show.html.haml
- provide :title, @event.title
%header
  %h1= @event.title
  %ul.actions
    %li= link_to "Edit Event", edit_event_path(@event), class: "edit" if policy(@event).edit?
    %li=link_to "Delete Event", @event, method: :delete, data: { confirm: "Are you sure?"},
    class: "delete" if policy(@event).destroy?
    - unless @event.seats_left?
      %li= link_to  "Register", event_attendances_path(@event), method: :post, class: "new"
    - else
      %li.label.label-danger.text-uppercase No Seats Available

.row
  .col-sm-9
    = image_tag image_present(@event, height: 1080, width: 500), class: "event-image center-block"
    .event-meta
      %h
        %span.event-start
          %strong Starts
          = format_time @event.start_date
      %p
        %span.event-end
          %strong= format_time @event.end_date

    .event-details
      %h3 Event Details
      %p= @event.description

    %header
      %h3 Comments

    #comments
      - if @event.comments.any?
        .text-center
          = will_paginate @comments
        = render @comments

      - else
        %p There are no comments

    = render "comments/comment_form", event: @event, comment: @comment if policy(@comment).create?

  .col-sm-3
    .sidebar
      %h4.organizer= link_to @event.organizer.username, user_path(@event.organizer)
      %p
        %span.event-venue= @event.venue.concat(",")
        %strong= @event.location
    %hr

    .sidebar
      %h4.tags
        - if @event.tags.any?
          = render @event.tags,event: @event
    %hr
    .sidebar
      %h4.attendees
        Attendees
        %span.pull-right=@event.attendees.count
        .clearfix
        %span.label.label-default.font-small.pull-right{:class => "#{hidden? @event}"}
          = succeed " Available" do
            = pluralize @event.seats_left, "Seat"
    %hr
    .sidebar
      %h4.likes Likes
      = succeed " " do
        = link_to event_likes_path(@event, like: "like"), method: :post do
          %span#like= @event.likes_total
      = precede " " do
        = link_to event_likes_path(@event, like: "dislike"), method: :post do
          %span#dislike= @event.dislikes_total