config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  root 'application#index'
    resources :users, :only => [:index]
    resources :categories, :except => [:show]
    resources :comments, :only => [:index]
    resources :comments, :only => [:index]
    resources :attendances,:only => [:index]
    resources :likes, :only => [:index]
  end

  devise_for :users
root 'home#index'

  resources :events do
    resources :comments
    resources :attendances, only: [:create]
    resources :likes, :only => [:create]
    resources :tags, :only => [:show]
  end

  resources :users, only: [:show]
  resources :categories, :only => [:show]
mount ActionCable.server => '/cable'
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin?
  skip_after_action :verify_authorized

  def index
    @users =User.all
    @events = Event.all
    @categories = Category.all
    @comments = Comment.all
    @attendances = Attendance.all
    @likes =Like.all
  end

  private
  def authorize_admin?
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, :alert => "You mustbe an admin to to execute that"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :exception

  include Pundit


  after_action :verify_authorized, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized



  private


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:email, :password, :password_confirmation, :first_name, :last_name, :username, :organization_name)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :username, :organization_name)
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform that action"
    redirect_to(request.referrer || root_path)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title page_title
    default_title = "EventsBoard - Create Events to Socialize"
    page_title.empty?  ? default_title : "#{page_title} | #{default_title}"
  end

  def format_time event
    event.strftime("%A, %d %b %Y %l:%M %p")
  end

  def active? path

    if  current_page? path
        "active"
    else
      ""
    end
  end

  def active_user_id? user

    active? "/users/#{user.id}"


  end

def admins_only(&block)
  block.call if current_user.try(:admin?)
end

  def gravatar_for user
    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"

  end

end

app/views/admin/application/index.html.haml
.row
  .col-sm-3.admin
    .admin-sidebar
      .user-panel
        .pull-left.image
          = image_tag   gravatar_for(current_user), width: 20, class: "img-circle"
        .pull-left.info
          %p= current_user.full_name
    %ul.admin-menu
      %li.text-uppercase.text-center.header Main Navigation
      %li
        = link_to admin_users_path do
          = fa_icon "users"
          %span Users
          %span.label.label-primary.pull-right= @users.count
      %li
        = link_to admin_categories_path do
          = fa_icon "th"
          %span Categories
          %span.label.label-info.pull-right= @categories.count
      %li
        = link_to admin_attendances_path do
          = fa_icon "user"
          %span Attendees
          %span.label.label-danger.pull-right=   @attendances.count
      %li
        = link_to events_path do
          = fa_icon "calendar"
          %span Events
          %span.label.label-warning.pull-right= @events.count
      %li
        = link_to "#" do
          = fa_icon "tag"
          %span Tags
          %span.label.label-default.pull-right tags
      %li
        = link_to admin_comments_path do
          = fa_icon "comments"
          %span Comments
          %span.label.label-primary.pull-right= @comments.count
      %li
        = link_to admin_likes_path do
          = fa_icon "heart"
          %span Likes
          %span.label.label-danger.pull-right= @likes.count
  .col-sm-9
    %header
      %h1
        Dashboard
        %small Control Panel
    %h4 Welcome to Admin Dashboard of Eventsboard