config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  root 'application#index'
    resources :users, :only => [:index]
    resources :categories, :except => [:show]
    resources :comments, :only => [:index]
    resources :comments, :only => [:index]
    resources :attendances,:only => [:index]
    resources :likes, :only => [:index]
  end

  devise_for :users
root 'home#index'

  resources :events do
    resources :comments
    resources :attendances, only: [:create]
    resources :likes, :only => [:create]
    resources :tags, :only => [:show]
  end

  resources :users, only: [:show]
  resources :categories, :only => [:show]
mount ActionCable.server => '/cable'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name
  has_many :events

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
before_action :set_category, :only =>  [:edit, :update, :destroy]
def index
  super
  @categories = Category.order(:name)
end

  def new
@category =Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, :notice => 'Category has been created'
    else
      flash.now[:alert] = "Category hasn't been created"
      render 'new'
    end

  end

  def edit

  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, :notice => "Category has been updated"
    else
      flash.now[:alert] = "Category has not been updated"
      render 'edit'
    end

  end

  def destroy
 @category.destroy
    redirect_to admin_categories_path, :alert => "Category has been deleted"

  end

  private

def set_category
  @category = Category.friendly.find(params[:id])
end

def category_params
  params.require(:category).permit(:name, :summary)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, :only => [:show]
  skip_after_action :verify_authorized

  def show
    @categories = Category.order(:name)
    @category_events = @category.events.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  private
  def set_category
@category = Category.friendly.find(params[:id])
  end

rescue ActiveRecord::RecordNotFound
  flash[:alert] = "The category you were looking for does not exist"
  redirect_to(request.referrer || events_url )
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def active_category? cat

    active? "/categories/#{cat.id}"


  end
end

app/views/admin/categories/_form.html.haml
.row
  .col-sm-8.col-sm-offset-2
    = simple_form_for([:admin, category]) do |f|

      = f.input :name

      = f.input :summary

      = f.button :submit, class: "btn btn-primary"

app/views/admin/categories/edit.html.haml
%header
  %h1
    Edit category
    = surround '(',')'  do
      %small= (@category.name)
= render "form", category: @category

app/views/admin/categories/index.html.haml
%header
  %h1 Categories
  - admins_only do
    %ul.actions
      %li= link_to "New category", new_admin_category_path, class: "new"

%table.table-responsive.table.table-striped
  %thead
    %tr
      %th Name
      %th Created
      %th Events
      %th{ :colspan => 3}

  %tbody
    - @categories.each do |cat|
      %tr
        %td= cat.name
        %td= format_time cat.created_at
        %td= 'Events'
        %td
          = link_to "View",  category_path(cat)
          = surround " | "  do
            = link_to "Edit", edit_admin_category_path(cat)
          = link_to "Delete", admin_category_path(cat),
          :method => :delete,data: {confirm: "Are you sure?"}

app/views/admin/categories/new.html.haml
%h1 New Category

= render "form", category: @category