config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  root 'application#index'
    resources :users, :only => [:index]
    resources :categories, :except => [:show]
    resources :comments, :only => [:index]
    resources :comments, :only => [:index]
    resources :attendances,:only => [:index]
    resources :likes, :only => [:index]
  end

  devise_for :users
root 'home#index'

  resources :events do
    resources :comments
    resources :attendances, only: [:create]
    resources :likes, :only => [:create]
    resources :tags, :only => [:show]
  end

  resources :users, only: [:show]
  resources :categories, :only => [:show]
mount ActionCable.server => '/cable'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name
  has_many :events

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
before_action :set_category, :only =>  [:edit, :update, :destroy]
def index
  super
  @categories = Category.order(:name)
end

  def new
@category =Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, :notice => 'Category has been created'
    else
      flash.now[:alert] = "Category hasn't been created"
      render 'new'
    end

  end

  def edit

  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, :notice => "Category has been updated"
    else
      flash.now[:alert] = "Category has not been updated"
      render 'edit'
    end

  end

  def destroy
 @category.destroy
    redirect_to admin_categories_path, :alert => "Category has been deleted"

  end

  private

def set_category
  @category = Category.friendly.find(params[:id])
end

def category_params
  params.require(:category).permit(:name, :summary)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, :only => [:show]
  skip_after_action :verify_authorized

  def show
    @categories = Category.order(:name)
    @category_events = @category.events.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  private
  def set_category
@category = Category.friendly.find(params[:id])
  end

rescue ActiveRecord::RecordNotFound
  flash[:alert] = "The category you were looking for does not exist"
  redirect_to(request.referrer || events_url )
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def active_category? cat

    active? "/categories/#{cat.id}"


  end
end

app/views/categories/show.html.haml
- provide(:title, @category.name)

%header
  %h1.text-uppercase= @category.name  + " Events"

  %ul.actions
    - admins_only do
      %li= link_to "Edit Category", edit_admin_category_path(@category), class: "edit"
      %li= link_to "Delete Category", admin_category_path(@category), method: :delete, date: { confirm: "Are you sure you want to delete this category?"},
      class: "delete"


.row
  .col-sm-3.pull-right
    .sidebar
      %h3.discover Discover
      %ul.nav.nav-pills.nav-stacked
        %li{:class => "#{active? events_path}"}
          = link_to "All EVENTS", events_path
        - @categories.each do |cat|
          %li{:class => "#{active_category?(cat)} text-uppercase"}= link_to cat.name, category_path(cat)

  .col-sm-9

    .search
      %h4 Discover and register to attend your favourite events right here
      = form_tag events_path, class: "form-horizontal", method: :get do

        .form-group.form-group-lg
          .col-sm-10
            = text_field_tag :query, params[:query], placeholder: "search events here", autofocus: true, class: "form-control"
          .col-sm-2
            = submit_tag "Find", class: "btn btn-default btn-lg"
            - if params[:query]
              = link_to "Clear", events_path

    - @category_events.each do |event|
      .col-sm-9.pull-left
        = link_to  event do
          .events
            .row
              .col-sm-3
                = image_tag image_present(event, height: 400, width: 200), class: "event-image"

              .col-sm-9
                %h3.event-title= event.title
                %p
                  %span.event-venue= event.venue.concat("-")
                  %strong= event.location
                %p.lead-time
                  %span.event-start= format_time event.start_date
                  %span.pull-right Organized by #{event.organizer.username}

= will_paginate @category_events